/**
 * PnlJugador.java
 */
package utileria;

import objetosNegocio.Jugador;
import java.awt.Color;
import java.awt.Dimension;

/**
 * JPanel que despliega la informacion de un jugador.
 * 
 * @author Abrahan Barrios, Victor Torres, Ana Rios
 */
public class PnlJugador extends javax.swing.JPanel {

    /**
     * Instancia del jugador al desplegar.
     */
    private Jugador jugador;

    /**
     * Crea PnlJugador.
     */
    public PnlJugador(Jugador jugador) {
        
        initComponents();
        this.setSize(new Dimension(280, 80));
        this.jugador = jugador;
        this.lblNombre.setText(this.jugador.getNombre());
        this.labelPtj.setText(this.jugador.getPuntaje() + "");
        
        if(this.jugador.getColor() != null){
            this.setBackground(this.jugador.getColor());
        }
    }
    
    /**
     * Establece el jugador.
     * @param jugador 
     */
    public void setJugador(Jugador jugador){
        this.jugador = jugador;
    }
    
    /**
     * Establece el puntaje de un jugador.
     * @param puntaje 
     */
    public void setPuntaje(int puntaje){
        this.jugador.setPuntaje(puntaje);
        this.labelPtj.setText(puntaje + "");
        this.labelPtj.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelPtj = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();

        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setFocusable(false);

        labelPtj.setFont(new java.awt.Font("Goudy Stout", 1, 24)); // NOI18N
        labelPtj.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPtj.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        labelPtj.setMaximumSize(new java.awt.Dimension(50, 50));
        labelPtj.setMinimumSize(new java.awt.Dimension(50, 50));
        labelPtj.setPreferredSize(new java.awt.Dimension(50, 50));

        lblNombre.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelPtj, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelPtj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelPtj;
    private javax.swing.JLabel lblNombre;
    // End of variables declaration//GEN-END:variables
}