/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package timbiriche;

import java.awt.Color;
import static javafx.scene.paint.Color.color;
import javax.swing.JOptionPane;
import objetosNegocio.Jugador;

/**
 *
 * @author Abrahan Barrios
 */
public class FrmUsuario extends javax.swing.JFrame {

    /**
     * Creates new form FrmUsuario
     */
    private String colores[];
    Jugador jugador;
    String ip = null;
    String puerto = null;
    String green=null,red=null,blue=null, yellow=null;
    
    public FrmUsuario() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setTitle("Usuario");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlUsuario = new javax.swing.JPanel();
        lblJugador = new javax.swing.JLabel();
        btnAtras2 = new javax.swing.JButton();
        txtUsuario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnRojo = new javax.swing.JRadioButton();
        btnAzul = new javax.swing.JRadioButton();
        btnVerde = new javax.swing.JRadioButton();
        btnAmarillo = new javax.swing.JRadioButton();
        btnContinuar = new javax.swing.JButton();
        lblSelec = new javax.swing.JLabel();
        lblSelec1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtIp = new javax.swing.JTextField();
        txtPuerto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Usuario");

        pnlUsuario.setBackground(new java.awt.Color(0, 102, 204));

        lblJugador.setFont(new java.awt.Font("Gill Sans Ultra Bold", 1, 36)); // NOI18N
        lblJugador.setForeground(new java.awt.Color(255, 255, 255));
        lblJugador.setText("Jugador");
        lblJugador.setToolTipText("");

        btnAtras2.setBackground(new java.awt.Color(204, 204, 204));
        btnAtras2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnAtras2.setForeground(new java.awt.Color(0, 51, 51));
        btnAtras2.setText("ATRAS");
        btnAtras2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtras2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Nombre");

        btnRojo.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btnRojo.setForeground(new java.awt.Color(204, 0, 0));
        btnRojo.setText("Rojo");
        btnRojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRojoActionPerformed(evt);
            }
        });

        btnAzul.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btnAzul.setForeground(new java.awt.Color(0, 0, 255));
        btnAzul.setText("Azul");
        btnAzul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAzulActionPerformed(evt);
            }
        });

        btnVerde.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btnVerde.setForeground(new java.awt.Color(0, 153, 0));
        btnVerde.setText("Verde");
        btnVerde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerdeActionPerformed(evt);
            }
        });

        btnAmarillo.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        btnAmarillo.setForeground(new java.awt.Color(255, 204, 0));
        btnAmarillo.setText("Amarillo");
        btnAmarillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAmarilloActionPerformed(evt);
            }
        });

        btnContinuar.setBackground(new java.awt.Color(204, 204, 204));
        btnContinuar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnContinuar.setForeground(new java.awt.Color(0, 51, 51));
        btnContinuar.setText("UNIRSE A PARTIDA");
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });

        lblSelec.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblSelec.setForeground(new java.awt.Color(255, 255, 255));
        lblSelec.setText("Seleccione un color");

        lblSelec1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblSelec1.setForeground(new java.awt.Color(255, 255, 255));
        lblSelec1.setText("Comunicación");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Dirección IP");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Puerto");

        javax.swing.GroupLayout pnlUsuarioLayout = new javax.swing.GroupLayout(pnlUsuario);
        pnlUsuario.setLayout(pnlUsuarioLayout);
        pnlUsuarioLayout.setHorizontalGroup(
            pnlUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUsuarioLayout.createSequentialGroup()
                .addGroup(pnlUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlUsuarioLayout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(lblJugador))
                    .addGroup(pnlUsuarioLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUsuarioLayout.createSequentialGroup()
                .addContainerGap(78, Short.MAX_VALUE)
                .addGroup(pnlUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUsuarioLayout.createSequentialGroup()
                        .addGroup(pnlUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlUsuarioLayout.createSequentialGroup()
                                .addComponent(btnAtras2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63)
                                .addComponent(btnContinuar))
                            .addGroup(pnlUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pnlUsuarioLayout.createSequentialGroup()
                                    .addComponent(btnRojo)
                                    .addGap(33, 33, 33)
                                    .addComponent(btnVerde)
                                    .addGap(35, 35, 35)
                                    .addComponent(btnAzul)
                                    .addGap(31, 31, 31)
                                    .addComponent(btnAmarillo))
                                .addGroup(pnlUsuarioLayout.createSequentialGroup()
                                    .addGap(117, 117, 117)
                                    .addComponent(lblSelec))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUsuarioLayout.createSequentialGroup()
                                    .addComponent(lblSelec1)
                                    .addGap(111, 111, 111))))
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUsuarioLayout.createSequentialGroup()
                        .addGroup(pnlUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlUsuarioLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(49, 49, 49))
                            .addGroup(pnlUsuarioLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(pnlUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPuerto, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                            .addComponent(txtIp))
                        .addGap(119, 119, 119))))
        );
        pnlUsuarioLayout.setVerticalGroup(
            pnlUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUsuarioLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblJugador)
                .addGap(32, 32, 32)
                .addGroup(pnlUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(30, 30, 30)
                .addComponent(lblSelec)
                .addGap(18, 18, 18)
                .addGroup(pnlUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAzul)
                    .addComponent(btnRojo)
                    .addComponent(btnVerde)
                    .addComponent(btnAmarillo))
                .addGap(18, 18, 18)
                .addComponent(lblSelec1)
                .addGap(28, 28, 28)
                .addGroup(pnlUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIp, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(jLabel2))
                .addGap(14, 14, 14)
                .addGroup(pnlUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPuerto, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(jLabel3))
                .addGap(24, 24, 24)
                .addGroup(pnlUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnContinuar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAtras2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed
        // TODO add your handling code here:
        if(!btnAmarillo.isSelected()&&!btnAzul.isSelected()&&!btnVerde.isSelected()&&!btnRojo.isSelected()){
            JOptionPane.showMessageDialog(this, "Elige un color!!! ", "Espera",JOptionPane.ERROR_MESSAGE);
            return;
        }

        if(txtUsuario.getText().equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(this, "Ingresa un Nombre de Jugador!!! ", "Espera",JOptionPane.ERROR_MESSAGE);
            return;
        }else{
            jugador= new Jugador(txtUsuario.getText(), 0); 
             
            if (colores[0] != null) {
                String color =colores[0];
                Color c=null;
                if (color.equals("RED")) {
                    c = Color.RED;
                }
                
                if (color.equals("BLUE")) {
                    c = Color.BLUE;
                }
                
                if (color.equals("GREEN")) {
                    c = Color.GREEN;
                }
                
                if (color.equals("YELLOW")) {
                    c = Color.YELLOW;
                }
                
            jugador.setColor(c);
            System.out.println("Color de Jugador > "+jugador.getColor());
        }

        if(txtIp.getText().equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(this, "Ingresa la dirección IP de la partida!!! ", "Espera",JOptionPane.ERROR_MESSAGE);
            return;
        }else{
            ip= txtIp.getText();
        }

        if(txtIp.getText().equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(this, "Ingresa el puerto al cual te conectaras!!! ", "Espera",JOptionPane.ERROR_MESSAGE);
            return;
        }else{
            puerto= txtPuerto.getText();
        }

        FrmSalaEspera se = FrmSalaEspera.getInstance();
  
        if(se.ejecutarConexion(jugador, ip, Integer.valueOf(puerto))){
            se.setVisible(true);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(this,"No se pudo realizar la conexión con el servidor", "Fallo de Conexión", JOptionPane.ERROR_MESSAGE);
            se = null;
        }
        
        }

    }//GEN-LAST:event_btnContinuarActionPerformed

    private void btnAmarilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAmarilloActionPerformed
        // TODO add your handling code here:
        if(btnAzul.isSelected()){
            btnAzul.setSelected(false);
        }else if(btnVerde.isSelected()){
            btnVerde.setSelected(false);
        }else if(btnRojo.isSelected()){
            btnRojo.setSelected(false);
        }
        colores=new String[]{"YELLOW","RED","GREEN","BLUE"};
        
    }//GEN-LAST:event_btnAmarilloActionPerformed

    private void btnVerdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerdeActionPerformed
        // TODO add your handling code here:
        if(btnAmarillo.isSelected()){
            btnAmarillo.setSelected(false);
        }else if(btnAzul.isSelected()){
            btnAzul.setSelected(false);
        }else if(btnRojo.isSelected()){
            btnRojo.setSelected(false);
        }

        colores=new String[]{"GREEN","RED","YELLOW","BLUE"};
    }//GEN-LAST:event_btnVerdeActionPerformed

    private void btnAzulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAzulActionPerformed
        // TODO add your handling code here:
        if(btnAmarillo.isSelected()){
            btnAmarillo.setSelected(false);
        }else if(btnVerde.isSelected()){
            btnVerde.setSelected(false);
        }else if(btnRojo.isSelected()){
            btnRojo.setSelected(false);
        }

         colores=new String[]{"BLUE","RED","YELLOW","GREEN"};
    }//GEN-LAST:event_btnAzulActionPerformed

    private void btnRojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRojoActionPerformed
        // TODO add your handling code here:
        if(btnAmarillo.isSelected()){
            btnAmarillo.setSelected(false);
        }else if(btnAzul.isSelected()){
            btnAzul.setSelected(false);
        }else if(btnVerde.isSelected()){
            btnVerde.setSelected(false);
        }

        colores=new String[]{"RED","BLUE","YELLOW","GREEN"};
    }//GEN-LAST:event_btnRojoActionPerformed

    private void btnAtras2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtras2ActionPerformed
        // TODO add your handling code here:
        FrmInicio i= new FrmInicio();
        i.setLocationRelativeTo(null);
        i.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAtras2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnAmarillo;
    private javax.swing.JButton btnAtras2;
    private javax.swing.JRadioButton btnAzul;
    private javax.swing.JButton btnContinuar;
    private javax.swing.JRadioButton btnRojo;
    private javax.swing.JRadioButton btnVerde;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblJugador;
    private javax.swing.JLabel lblSelec;
    private javax.swing.JLabel lblSelec1;
    private javax.swing.JPanel pnlUsuario;
    private javax.swing.JTextField txtIp;
    private javax.swing.JTextField txtPuerto;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
